### ISSUE TITLE
Update all group columns

### ISSUE THREAD

**Issue by usu-access** [usu-accessibility/PopeMondaySync#4]
If a website is in a group with three group levels: 
A1 | A2 | A3

But then gets moved to a site with only 2 group levels: 
B1 | B2

Then when we do an update it shows up as: 
B1 | B2 | A3

But should be: 
B1 | B2 | 

Here is a video explanation: 
https://www.loom.com/share/8186888bf9214cfdaabebd7e91fa579b

**Comment by cartersingle** [comment]
Bug fixed with latest update. Cause was a missing argument inside of the update groups module.
