### ISSUE TITLE
Stuck vs Not Found

### ISSUE THREAD

**Issue by usu-access** [usu-accessibility/PopeMondaySync#5]
Currently when a site is not found it is marked as "Stuck" which denotes it is not able to check for some reason. 

Instead, I am going to recommend we change the label to when something is not found to "Not Found". 

If Stuck is still needed - to denote when there is an error checking, we can keep it.

**Comment by cartersingle** [comment]
Updated with latest push. Now changes to not found when data isn't found in Popetech or monday.
